Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -5,15 +5,24 @@ phases:
     commands:
       - echo "📦 Installing Newman..."
       - npm install -g newman newman-reporter-htmlextra
+
   build:
     commands:
       - echo "🚀 Running API tests with Newman..."
       # chạy newman, luôn trả về 0 để không dừng build
-      - newman run Postman_Collections/collection.json --reporters cli,htmlextra --reporter-htmlextra-export report.html || true
+      - newman run Postman_Collections/colletionjson.json \
+          --reporters cli,htmlextra \
+          --reporter-htmlextra-export report.html || true
+
+      # lấy exit code thực của newman
       - TEST_EXIT_CODE=${PIPESTATUS[0]}
-      - echo "✅ Test completed. Uploading report to S3..."
+
+      - echo "📂 Checking report file..."
       - ls -l report.html || echo "⚠️ report.html not found"
+
+      - echo "☁️ Uploading report to S3..."
       - aws s3 cp report.html s3://tiki-api-report-bucket/$(date +%F_%H-%M)-report.html --region ap-southeast-1
+
       - |
         if [ $TEST_EXIT_CODE -ne 0 ]; then
           echo "❌ Test failed! Sending SNS alert..."
